/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.Cliente;
import dominio.ClienteBorrar;
import dominio.CuentaBancaria;
import excepciones.PersistenciaException;
import implementaciones.CuentasBancariasDAO;
import interfaces.IConexionBD;
import interfaces.ICuentasBancariasDAO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;
import org.mindrot.jbcrypt.BCrypt;
import utils.ConfiguracionPaginado;

/**
 *
 * @author Elkur
 */
public class CuentasForm extends javax.swing.JFrame {

    /**
     * Creates new form EditarClienteForm
     */
    private static final Logger LOG = Logger.getLogger(CuentasForm.class.getName());
    private final ICuentasBancariasDAO cuentasBancariasDAO;
    private ConfiguracionPaginado configPaginado;
    private Cliente cliente;
    private final IConexionBD conBD;

    public CuentasForm(IConexionBD conBD, Cliente cliente) {
        this.cuentasBancariasDAO = new CuentasBancariasDAO(conBD);
        this.conBD = conBD;
        this.configPaginado = new ConfiguracionPaginado();
        this.cliente = cliente;
        initComponents();
        this.llenarTablaCuentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background3 = new javax.swing.JPanel();
        head3 = new javax.swing.JPanel();
        txtBienvenida = new javax.swing.JLabel();
        panelTablaCuentas = new javax.swing.JScrollPane();
        tablaCuentas = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        brnDesactivarCuenta = new javax.swing.JButton();
        btnRetiroSinTarjeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background3.setBackground(new java.awt.Color(255, 255, 255));
        background3.setMaximumSize(new java.awt.Dimension(600, 400));
        background3.setMinimumSize(new java.awt.Dimension(600, 400));
        background3.setPreferredSize(new java.awt.Dimension(600, 400));
        background3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head3.setBackground(new java.awt.Color(0, 102, 255));

        txtBienvenida.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        txtBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        txtBienvenida.setText("Bienvenido");

        javax.swing.GroupLayout head3Layout = new javax.swing.GroupLayout(head3);
        head3.setLayout(head3Layout);
        head3Layout.setHorizontalGroup(
            head3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtBienvenida)
                .addContainerGap(460, Short.MAX_VALUE))
        );
        head3Layout.setVerticalGroup(
            head3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtBienvenida)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        background3.add(head3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 90));

        tablaCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Cuenta", "Fecha Apertura", "Saldo MXN", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCuentas.setColumnSelectionAllowed(true);
        panelTablaCuentas.setViewportView(tablaCuentas);
        tablaCuentas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        background3.add(panelTablaCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 560, 210));

        btnRegresar.setBackground(new java.awt.Color(0, 102, 255));
        btnRegresar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        background3.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 20));

        brnDesactivarCuenta.setBackground(new java.awt.Color(0, 102, 255));
        brnDesactivarCuenta.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        brnDesactivarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        brnDesactivarCuenta.setText("Desactivar Cuenta");
        brnDesactivarCuenta.setBorder(null);
        brnDesactivarCuenta.setBorderPainted(false);
        brnDesactivarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnDesactivarCuentaActionPerformed(evt);
            }
        });
        background3.add(brnDesactivarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 130, 40));

        btnRetiroSinTarjeta.setBackground(new java.awt.Color(0, 102, 255));
        btnRetiroSinTarjeta.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnRetiroSinTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        btnRetiroSinTarjeta.setText("Retiro Sin Tarjeta");
        btnRetiroSinTarjeta.setBorder(null);
        btnRetiroSinTarjeta.setBorderPainted(false);
        btnRetiroSinTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroSinTarjetaActionPerformed(evt);
            }
        });
        background3.add(btnRetiroSinTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuPrincipalForm menuPrincipal = new MenuPrincipalForm(this.conBD, cliente);
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void brnDesactivarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnDesactivarCuentaActionPerformed
        this.desactivar();
    }//GEN-LAST:event_brnDesactivarCuentaActionPerformed

    private void btnRetiroSinTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroSinTarjetaActionPerformed
        CrearRetiroSinCuentaForm crearRetiroSinCuentaForm = new CrearRetiroSinCuentaForm(this.conBD, this, this.cliente);
        crearRetiroSinCuentaForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRetiroSinTarjetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background3;
    private javax.swing.JButton brnDesactivarCuenta;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRetiroSinTarjeta;
    private javax.swing.JPanel head3;
    private javax.swing.JScrollPane panelTablaCuentas;
    private javax.swing.JTable tablaCuentas;
    private javax.swing.JLabel txtBienvenida;
    // End of variables declaration//GEN-END:variables

    private void llenarTablaCuentas() {
        try {

            List<CuentaBancaria> listaCuentas = this.cuentasBancariasDAO.consultar(this.configPaginado, this.cliente.getId());
            DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaCuentas.getModel();
            modeloTabla.setRowCount(0);

            for (CuentaBancaria cuenta : listaCuentas) {
                Object[] fila = {
                    cuenta.getNoCuenta(),
                    cuenta.getFechaApertura(),
                    cuenta.getSaldoMXN(),
                    cuenta.getEstadoCuenta()
                };
                modeloTabla.addRow(fila);

            }

        } catch (PersistenciaException e) {
            LOG.log(Level.SEVERE, e.getMessage());
        }
    }

    private void desactivar() {
        
        String input = this.pedirInputUsuario("Desactivar Cuenta", "Ingresa el numero de cuenta");
        try {
            CuentaBancaria cuentaBancaria = this.cuentasBancariasDAO.consultar(input);
            
            // TODO pedir password
            String password = pedirPassword();
            if (!validarPassword(password)) {
                this.mostrarError("Contraseña invalida");
                return;
            }
            
            
            cuentaBancaria.desactivarCuenta();
            this.cuentasBancariasDAO.actualizar(cuentaBancaria);
            this.llenarTablaCuentas();
        } catch (PersistenciaException e) {
            LOG.log(Level.SEVERE, e.getMessage());
            this.mostrarError("Ingresa un Numero de Cuenta valido");
        }
    }

    private void mostrarError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void mostrarMensajeExito(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Exito", JOptionPane.PLAIN_MESSAGE);
    }

    private String pedirInputUsuario(String titulo, String texto) {
        return (String) JOptionPane.showInputDialog(this, texto, titulo, JOptionPane.QUESTION_MESSAGE);
    }

    private String pedirPassword() {
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Ingresa una contraseña:");
        JPasswordField pass = new JPasswordField(10);
        panel.add(label);
        panel.add(pass);
        String[] options = new String[]{"OK", "Cancelar"};
        int option = JOptionPane.showOptionDialog(null, panel, "Credenciales",
                JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options, options[1]);
        // pressing OK button
        if (option == 0) {
            char[] password = pass.getPassword();
            return new String(password);
        }
        return "";
    }

    private boolean validarPassword(String passwordCandidato) {
        System.out.println(passwordCandidato);
        System.out.println(cliente.getContrasenia());
        return BCrypt.checkpw(passwordCandidato, cliente.getContrasenia());
    }
}
