/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.ClienteBorrar;
import dominio.CuentaBancaria;
import excepciones.PersistenciaException;
import implementacion.CuentasBancariasDAO;
import interfaces.ICuentasBancariasDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utils.Conversiones;
import utils.Validaciones;

/**
 *
 * @author Elkur
 */
public class MenuPrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form EditarClienteForm
     */
    private static final Logger LOG = Logger.getLogger(MenuPrincipalForm.class.getName());
    private ClienteBorrar cliente;
    private final ICuentasBancariasDAO cuentasBancariasDAO;
//    public MenuPrincipalForm(IClientesDAO clientesDAO) {

    public MenuPrincipalForm(ICuentasBancariasDAO cuentasBancariasDAO, ClienteBorrar cliente) {
        this.cliente = cliente;
        this.cuentasBancariasDAO = cuentasBancariasDAO;
        initComponents();
        cargarMensajeBienvenida();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background3 = new javax.swing.JPanel();
        head3 = new javax.swing.JPanel();
        txtBienvenida = new javax.swing.JLabel();
        btnHistorialActividad = new javax.swing.JButton();
        btnTransferencia = new javax.swing.JButton();
        btnCrearCuentaBancaria = new javax.swing.JButton();
        btnMisCuentas = new javax.swing.JButton();
        imgMenuPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BancoTransacciones");
        setResizable(false);

        background3.setBackground(new java.awt.Color(255, 255, 255));
        background3.setMaximumSize(new java.awt.Dimension(600, 400));
        background3.setMinimumSize(new java.awt.Dimension(600, 400));
        background3.setPreferredSize(new java.awt.Dimension(600, 400));
        background3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head3.setBackground(new java.awt.Color(0, 102, 255));

        txtBienvenida.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        txtBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        txtBienvenida.setText("Bienvenido");

        javax.swing.GroupLayout head3Layout = new javax.swing.GroupLayout(head3);
        head3.setLayout(head3Layout);
        head3Layout.setHorizontalGroup(
            head3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtBienvenida)
                .addContainerGap(463, Short.MAX_VALUE))
        );
        head3Layout.setVerticalGroup(
            head3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtBienvenida)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        background3.add(head3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 90));

        btnHistorialActividad.setBackground(new java.awt.Color(0, 102, 255));
        btnHistorialActividad.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnHistorialActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialActividad.setText("Historial Actividad");
        btnHistorialActividad.setBorder(null);
        btnHistorialActividad.setBorderPainted(false);
        btnHistorialActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActividadActionPerformed(evt);
            }
        });
        background3.add(btnHistorialActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 120, 40));

        btnTransferencia.setBackground(new java.awt.Color(0, 102, 255));
        btnTransferencia.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        btnTransferencia.setText("Transferencia");
        btnTransferencia.setBorder(null);
        btnTransferencia.setBorderPainted(false);
        btnTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferenciaActionPerformed(evt);
            }
        });
        background3.add(btnTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 100, 40));

        btnCrearCuentaBancaria.setBackground(new java.awt.Color(0, 102, 255));
        btnCrearCuentaBancaria.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnCrearCuentaBancaria.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuentaBancaria.setText("Crear Cuenta");
        btnCrearCuentaBancaria.setBorder(null);
        btnCrearCuentaBancaria.setBorderPainted(false);
        btnCrearCuentaBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaBancariaActionPerformed(evt);
            }
        });
        background3.add(btnCrearCuentaBancaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 40));

        btnMisCuentas.setBackground(new java.awt.Color(0, 102, 255));
        btnMisCuentas.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnMisCuentas.setForeground(new java.awt.Color(255, 255, 255));
        btnMisCuentas.setText("Mis Cuentas");
        btnMisCuentas.setBorder(null);
        btnMisCuentas.setBorderPainted(false);
        btnMisCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisCuentasActionPerformed(evt);
            }
        });
        background3.add(btnMisCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, 40));
        background3.add(imgMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 600, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMisCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisCuentasActionPerformed
        CuentasForm cuentasForm = new CuentasForm(cuentasBancariasDAO, cliente);
        cuentasForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMisCuentasActionPerformed

    private void btnCrearCuentaBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaBancariaActionPerformed
        this.crearCuenta();
    }//GEN-LAST:event_btnCrearCuentaBancariaActionPerformed

    private void btnTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferenciaActionPerformed


    }//GEN-LAST:event_btnTransferenciaActionPerformed

    private void btnHistorialActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialActividadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background3;
    private javax.swing.JButton btnCrearCuentaBancaria;
    private javax.swing.JButton btnHistorialActividad;
    private javax.swing.JButton btnMisCuentas;
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JPanel head3;
    private javax.swing.JLabel imgMenuPrincipal;
    private javax.swing.JLabel txtBienvenida;
    // End of variables declaration//GEN-END:variables

    private void cargarMensajeBienvenida() {
        this.txtBienvenida.setText("Hola, " + this.cliente.getNombre() + "!");
    }

    /**
     * Pide al usuario un monto opcional e inserta la cuenta a la base de datos,
     * si es que el monto es valido.
     */
    private void crearCuenta() {
        String input = this.pedirInputUsuario("Crear Cuenta Bancaria", "Ingresa el monto inicial (Opcional)");

        CuentaBancaria cuentaBancaria = extraerDatosCuenta(input);

        try {
            System.out.println(cuentaBancaria.getSaldoMXN());
            CuentaBancaria cuentaCreada = this.cuentasBancariasDAO.insertar(cuentaBancaria, this.cliente);
            this.mostrarMensajeExito("Cuenta creada con No. " + cuentaCreada.getNoCuenta());
            System.out.println(this.cuentasBancariasDAO.consultar(cuentaCreada.getId()));
        } catch (PersistenciaException ex) {
            mostrarMensajeError("Error al crear cuenta");
            Logger.getLogger(MenuPrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private CuentaBancaria extraerDatosCuenta(String input) {
        if (input.isBlank()) {
            return new CuentaBancaria();
        } else {
            Double monto = Conversiones.crearMontoDeTexto(input);
            if (Validaciones.isPositivo(monto)) {
                return new CuentaBancaria(monto);
            } else {
                this.mostrarMensajeError("Ingresa un monto valido");
                this.crearCuenta();
            }

        }
        return null;
    }

    private void mostrarMensajeError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void mostrarMensajeExito(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Exito", JOptionPane.PLAIN_MESSAGE);
    }

    private String pedirInputUsuario(String titulo, String texto) {
        return (String) JOptionPane.showInputDialog(this, texto, titulo, JOptionPane.QUESTION_MESSAGE);
    }
}
