/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Elkur
 */
public class EditarClienteForm extends javax.swing.JFrame {

    /**
     * Creates new form EditarClienteForm
     */
    public EditarClienteForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background3 = new javax.swing.JPanel();
        head3 = new javax.swing.JPanel();
        txtEditar = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtCalle = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblCalle = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblContrasena = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblCodigoPostal = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        lblColonia1 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background3.setBackground(new java.awt.Color(255, 255, 255));
        background3.setMaximumSize(new java.awt.Dimension(600, 400));
        background3.setMinimumSize(new java.awt.Dimension(600, 400));
        background3.setPreferredSize(new java.awt.Dimension(600, 400));
        background3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head3.setBackground(new java.awt.Color(0, 102, 255));

        txtEditar.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        txtEditar.setForeground(new java.awt.Color(255, 255, 255));
        txtEditar.setText("Editar");

        javax.swing.GroupLayout head3Layout = new javax.swing.GroupLayout(head3);
        head3.setLayout(head3Layout);
        head3Layout.setHorizontalGroup(
            head3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head3Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(txtEditar)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        head3Layout.setVerticalGroup(
            head3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, head3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(txtEditar)
                .addGap(28, 28, 28))
        );

        background3.add(head3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 90));
        background3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 210, 10));

        txtCalle.setBackground(new java.awt.Color(255, 255, 255));
        txtCalle.setForeground(new java.awt.Color(51, 51, 51));
        txtCalle.setToolTipText("");
        txtCalle.setBorder(null);
        background3.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 210, 20));
        background3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 210, 10));

        lblCalle.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lblCalle.setForeground(new java.awt.Color(0, 0, 0));
        lblCalle.setText("Calle");
        background3.add(lblCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 90, 20));

        txtColonia.setBackground(new java.awt.Color(255, 255, 255));
        txtColonia.setForeground(new java.awt.Color(51, 51, 51));
        txtColonia.setToolTipText("");
        txtColonia.setBorder(null);
        background3.add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, 20));
        background3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 100, 10));

        lblContrasena.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(0, 0, 0));
        lblContrasena.setText("Contraseña");
        background3.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 80, 20));

        txtCodigoPostal.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoPostal.setForeground(new java.awt.Color(51, 51, 51));
        txtCodigoPostal.setToolTipText("");
        txtCodigoPostal.setBorder(null);
        background3.add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 100, 20));
        background3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 100, 10));

        lblCodigoPostal.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lblCodigoPostal.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigoPostal.setText("Codigo postal");
        background3.add(lblCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 90, 20));

        btnCambiar.setBackground(new java.awt.Color(0, 102, 255));
        btnCambiar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnCambiar.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiar.setText("Guardar");
        btnCambiar.setBorder(null);
        btnCambiar.setBorderPainted(false);
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        background3.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 80, 30));

        lblColonia1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lblColonia1.setForeground(new java.awt.Color(0, 0, 0));
        lblColonia1.setText("Colonia");
        background3.add(lblColonia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 50, 20));

        txtContrasena.setBackground(new java.awt.Color(255, 255, 255));
        txtContrasena.setBorder(null);
        background3.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 210, 20));

        btnCancelar.setBackground(new java.awt.Color(0, 102, 255));
        btnCancelar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        background3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarClienteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel background1;
    private javax.swing.JPanel background2;
    private javax.swing.JPanel background3;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel head;
    private javax.swing.JPanel head1;
    private javax.swing.JPanel head2;
    private javax.swing.JPanel head3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblCodigoPostal;
    private javax.swing.JLabel lblColonia1;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JLabel txtEditar;
    private javax.swing.JLabel txtRegistar;
    private javax.swing.JLabel txtRegistar1;
    private javax.swing.JLabel txtRegistar2;
    // End of variables declaration//GEN-END:variables
}
